core/models.py
from datetime import date

from . import db



"""
class Author:
    id: int primary key
    auth_firstname: str
    auth_lastname: str
    auth_birthdate: date
    auth_created: date
"""


class Author(db.Model):
	__tablename__ = "author"
	
	id = db.Column(db.Integer, primary_key=True)
	auth_firstname = db.Column(db.String(80), nullable=False)
	auth_lastname = db.Column(db.String(100), nullable=False)
	auth_birthdate = db.Column(db.Date, default=date.today())
	auth_created = db.Column(db.Date, default=date.today())

	def save(self):
		db.session.add(self)
		db.session.commit()

	def update(self, auth_firstname, auth_lastname, auth_birthdate):
		self.auth_firstname = auth_firstname
		self.auth_lastname = auth_lastname
		self.auth_birthdate = auth_birthdate
		db.session.commit()

	def delete(self):
		db.session.delete(self)
		db.session.commit()


"""
class Post:
    id: int primary key
    post_title: str
    post_subtitle: str
    post_content: str (Text)
    post_author: str
    post_posted: date
"""


class Post(db.Model):
	__tablename__ = "post"
	id = db.Column(db.Integer, primary_key=True)
	post_title = db.Column(db.String(80), nullable=False)
	post_subtitle = db.Column(db.String(100), nullable=False)
	post_content = db.Column(db.Text, nullable=False)
	post_author = db.Column(db.String(80), nullable=False)
	post_posted = db.Column(db.Date, default=date.today())

	def __str__(self):
		return self.post_title

	def save(self):
		db.session.add(self)
		db.session.commit()

	def update(self, post_title, post_subtitle, post_content, post_author):
		self.post_title = post_title
		self.post_content = post_subtitle
		self.post_content = post_content
		self.post_author = post_author
		db.session.commit()

	def delete(self):
		db.session.delete(self)
		db.session.commit()

core/__init__.py
import os
import logging as lg

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from config import config


db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)

    with app.app_context():

        from .views import post
        app.register_blueprint(post)

        return app

core/views.py
from flask import Blueprint, render_template

from .models import Post

post = Blueprint("post", __name__, url_prefix='/')

posts = Post.query.all()

@post.route("/")
def home_page():
    return render_template(
        "index.html",
        posts_all=posts[:4],
        page_title="Accueil",
        subheading="Bienvenu(e) sur Clean Blog"
    )


@post.route("/blog")
def blog_page():
    return render_template(
        "pages/blog/list.html",
        posts_all=posts,
        page_title="Blog",
        subheading="Liste des articles"
    )


@post.route("/blog/<int:post_id>")
def blog_detail_page(post_id):

    article = Post.query.get_or_404(post_id)
    
    return render_template(
        "pages/blog/detail.html",
        post=article,
        page_title=article.post_title,
        subheading=article.post_subtitle
    )


@post.route("/contact/")
def contact_page():
	return render_template(
        "pages/contact.html",
        page_title="Contact",
        subheading="Laissez-nous un message"
    )


@post.route("/support/")
def support_page():
    return render_template(
        "pages/support.html",
        page_title="Support",
        subheading="Besoin d'aides ?"
    )

core/templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}" />
		<title>{{ page_title }}</title>

		<script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />

        <link href="{{ url_for('static', filename="css/styles.css") }}" rel="stylesheet" />
	</head>

	<body>
		<!-- Navigation -->
		{% include "partial/_navbar.html" %}

		<!-- Page Header-->
		{% include "partial/_header.html" %}

		<!-- Main Content-->
		{% block page_content %}
		    <main class="container px-4 px-lg-5">
				<section class="row gx-4 gx-lg-5 justify-content-center">
					<div class="col-md-10 col-lg-8 col-xl-7">
						<!-- post single -->
						{% for post in posts_all %}
							{% include "partial/_post.html" %}
						{% endfor %}
				</section>
			</main>
		{% endblock page_content %}

		<!-- Footer-->
		{% include "partial/_footer.html" %}

		<!-- Core theme JS-->
        <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>

		<!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
	</body>
</html>

core/templates/pages/blog/detail.html
{% extends "index.html" %}

{% block page_content %}
    <article class="mb-4">
    	<div class="container px-4 px-lg-5">
    		<div class="row gx-4 gx-lg-5 justify-content-center">
    			<div class="col-md-10 col-lg-8 col-xl-7">
    				<p>{{ post.post_content }}</p>
    			</div>
    		</div>
    	</div>
    </article>
{% endblock page_content %}

core/templates/pages/blog/list.html
{% extends "index.html" %}

{% block page_content %}
	<main class="container px-4 px-lg-5">
		<section class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
			<!-- post single -->
			{% for post in posts_all %}
				{% include "partial/_post.html" %}
			{% endfor %}
		</section>
	</main>
{% endblock page_content %}

core/templates/pages/contact.html
{% extends "index.html" %}

{% block page_content %}
	<h1>{{ page_title }}</h1>
	<p>Aller sur ma page de <a href="{{ url_for('post.support_page') }}">Support</a></p>
{% endblock page_content %}

core/templates/pages/support.html
{% extends "index.html" %}

{% block page_content %}
    <h1>{{ page_title }}</h1>
	<p>Aller sur ma page d' <a href="{{ url_for('post.home_page') }}">Accueil</a></p>
{% endblock page_content %}

core/templates/partial/_footer.html
<footer class="border-top">
	<div class="container px-4 px-lg-5">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
				<ul class="list-inline text-center">
					<li class="list-inline-item">
						<a href="#!">
							<span class="fa-stack fa-lg">
								<i class="fas fa-circle fa-stack-2x"></i>
								<i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
							</span>
						</a>
					</li>
					<li class="list-inline-item">
						<a href="#!">
							<span class="fa-stack fa-lg">
								<i class="fas fa-circle fa-stack-2x"></i>
								<i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
							</span>
						</a>
					</li>
					<li class="list-inline-item">
						<a href="#!">
							<span class="fa-stack fa-lg">
								<i class="fas fa-circle fa-stack-2x"></i>
								<i class="fab fa-github fa-stack-1x fa-inverse"></i>
							</span>
						</a>
					</li>
				</ul>
				<div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
			</div>
		</div>
	</div>
</footer>

core/templates/partial/_header.html
<header class="masthead" style="background-image: url('{{ url_for('static', filename='img/home-bg.jpg') }}')">
	<div class="container position-relative px-4 px-lg-5">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
				<div class="post-heading">
					<h1>{{ page_title }}</h1>
					<span class="subheading">{{ subheading }}</span>
				</div>
			</div>
		</div>
	</div>
</header>

core/templates/partial/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
	<div class="container px-4 px-lg-5">
		<a class="navbar-brand" href="/">Clean Blog</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Menu
			<i class="fas fa-bars"></i>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ms-auto py-4 py-lg-0">
				<li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('post.blog_page') }}">Blog</a></li>
				<li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('post.contact_page') }}">Contact</a></li>
				<li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('post.support_page') }}">Support</a></li>
			</ul>
		</div>
	</div>
</nav>

core/templates/partial/_post.html
<article class="post-preview">
	<a href="{{ url_for('post.blog_detail_page', post_id=post.id) }}">
		<h2 class="post-title">{{ post.post_title }}</h2>
		<h3 class="post-subtitle">{{ post.post_subtitle }}</h3>
	</a>
	<p class="post-meta">
		Publié par
		<a href="#!">{{ post.post_author }}</a>
		le {{ post.post_posted }}
	</p>
</article>